### ISSUE TITLE
Symbolic link locations do no match

### ISSUE THREAD

**Issue by GreyMonkey56** [USBhost/build-tools-gcc#5]
relative to sources directory

    extract ${MPFR}.tar.xz ../${MPFR}
    extract ${GMP}.tar.xz ../${GMP}
    extract ${MPC}.tar.gz ../${MPC}

then cd gcc and
    ln -s -f ../${MPFR} mpfr
    ln -s -f ../${GMP} gmp
    ln -s -f ../${MPC} mpc

Won't work! either use ../../ in links or extract tar files into sources directory

**Comment by USBhost** [comment]
Have you tested if it does infact build?
I know it looks wrong at first glance
1: using ../../ will break building with tarballs.
Think about it, building with tarballs extracts everything to the root dictionary. The only things in the sources directory is the tarballs. ( the only thing that goes in it are git and tarballs )

2: Now building normal ( with git ). Here is where things start to look wrong.
At first we know gcc will be in the sources directory so using ../ looks wrong. GMP, MPFR, MPC are still extracted in the root dictionary ( so that didn't change ) and GCC is in the sources directory... so how is ../ is correct? take a look at https://github.com/USBhost/build-tools-gcc/blob/master/build#L408 That line links sources/gcc to the root directory. so bingo or ../ problem is fixed.

did i miss anything?

Edit: it seems your right... investigating

**Comment by GreyMonkey56** [comment]
This is what happens without the prpper symlinks

checking for the correct version of mpfr.h... no
configure: error: Building GCC requires GMP 4.2+, MPFR 2.4.0+ and MPC 0.8.0+.
Try the --with-gmp, --with-mpfr and/or --with-mpc options to specify
their locations.  Source code for these libraries can be found at
their respective hosting sites as well as at
ftp://gcc.gnu.org/pub/gcc/infrastructure/.  See also
http://gcc.gnu.org/install/prerequisites.html for additional info.  If
you obtained GMP, MPFR and/or MPC from a vendor distribution package,
make sure that you have installed both the libraries and the header
files.  They may be located in separate packages.
make: *** No rule to make target 'all-gcc'.  Stop.

Error while building gcc!
